import type { Product } from "@/lib/types";

export const categories = [
  "Elite trainer box",
  "Upc",
  "Booster",
  "Display",
  "Blister",
  "Coffret",
  "Protection",
] as const;

export const sampleProducts: Product[] = [
  {
    name: "Coffret Rayquaza Foudre Nacree",
    slug: "coffret-rayquaza-foudre-nacree",
    category: "Coffret",
    price: 5990,
    description:
      "Coffret collector avec booster exclusif et sleeves holo pour des tirages legendaires.",
    badge: "Collector",
    image: "/images/demo-1.svg",
    tags: ["Pokemon", "Collector"],
    featured: true,
    stock: 18,
  },
  {
    name: "Elite Trainer Box Luffy Sunburst",
    slug: "etb-luffy-sunburst",
    category: "Elite trainer box",
    price: 5490,
    description:
      "Pack complet pour demarrer One Piece TCG avec accessoires premium.",
    badge: "Nouveau",
    image: "/images/demo-2.svg",
    tags: ["One Piece"],
    featured: true,
    stock: 26,
  },
  {
    name: "UPC Pikachu Comet Rush",
    slug: "upc-pikachu-comet-rush",
    category: "Upc",
    price: 15900,
    description:
      "Ultimate premium collection, cartes promo, boosters et deck box ultra deluxe.",
    badge: "Ultra",
    image: "/images/demo-4.svg",
    tags: ["Pokemon"],
    featured: true,
    stock: 8,
  },
  {
    name: "Display Gear 5 Storm",
    slug: "display-gear-5-storm",
    category: "Display",
    price: 11900,
    description:
      "Display One Piece 24 boosters, parfait pour sceller un event.",
    badge: "Drop",
    image: "/images/demo-5.svg",
    tags: ["One Piece"],
    featured: true,
    stock: 12,
  },
  {
    name: "Booster Pokemon Cosmos Rift",
    slug: "booster-pokemon-cosmos-rift",
    category: "Booster",
    price: 590,
    description: "Booster classique pour booster ta collection cosmique.",
    badge: "Hot",
    image: "/images/demo-3.svg",
    tags: ["Pokemon"],
    stock: 140,
  },
  {
    name: "Booster One Piece Grand Line",
    slug: "booster-one-piece-grand-line",
    category: "Booster",
    price: 650,
    description: "Booster One Piece avec artset exclusif.",
    badge: "Hot",
    image: "/images/demo-2.svg",
    tags: ["One Piece"],
    stock: 120,
  },
  {
    name: "Blister Duo V-Star",
    slug: "blister-duo-v-star",
    category: "Blister",
    price: 1290,
    description: "Blister duo Pokemon pour pulls rapides.",
    image: "/images/demo-1.svg",
    tags: ["Pokemon"],
    stock: 60,
  },
  {
    name: "Blister One Piece Dawn",
    slug: "blister-one-piece-dawn",
    category: "Blister",
    price: 1390,
    description: "Blister One Piece, edition Dawn.",
    image: "/images/demo-2.svg",
    tags: ["One Piece"],
    stock: 44,
  },
  {
    name: "Display Pokemon Ether Prism",
    slug: "display-pokemon-ether-prism",
    category: "Display",
    price: 12900,
    description: "Display Pokemon 36 boosters pour les gros openings.",
    badge: "Pro",
    image: "/images/demo-5.svg",
    tags: ["Pokemon"],
    stock: 10,
  },
  {
    name: "Protection Hyper Shield",
    slug: "protection-hyper-shield",
    category: "Protection",
    price: 1490,
    description:
      "Set sleeves + toploader premium pour proteger tes pulls.",
    image: "/images/demo-6.svg",
    tags: ["Accessoires"],
    stock: 200,
  },
  {
    name: "Protection Vault Deckbox",
    slug: "protection-vault-deckbox",
    category: "Protection",
    price: 2490,
    description: "Deckbox rigide avec mousse anti choc.",
    image: "/images/demo-6.svg",
    tags: ["Accessoires"],
    stock: 70,
  },
  {
    name: "Elite Trainer Box Eevee Nova",
    slug: "etb-eevee-nova",
    category: "Elite trainer box",
    price: 5290,
    description: "ETB Pokemon avec dice et accessoires exclusifs.",
    badge: "Fan favorite",
    image: "/images/demo-3.svg",
    tags: ["Pokemon"],
    stock: 32,
  },
];
